### PR TITLE
Updates from testing

### PR DESCRIPTION
**Pull request by alerman**

### CODE REVIEW

File: datawave-micrometer/pom.xml [hunk 1]
```diff
@@ -12,8 +12,8 @@
     <artifactId>datawave-micrometer</artifactId>
 
     <properties>
-        <maven.compiler.source>17</maven.compiler.source>
```
Comment (ddanielr) [inline datawave-micrometer/pom.xml:15]: Can we keep it as `17` and just change the compiler target to `11`? 
That would allow it to match the current accumulo build process and future desired datawave build process.

File: datawave-micrometer/pom.xml [hunk 2]
```diff
@@ -12,8 +12,8 @@
...
-        <maven.compiler.target>17</maven.compiler.target>
+        <maven.compiler.source>11</maven.compiler.source>
+        <maven.compiler.target>11</maven.compiler.target>
```
Comment (ddanielr) [inline datawave-micrometer/pom.xml]:
```suggestion
        <maven.compiler.target>11</maven.compiler.target>
        <maven.compiler.release>11</maven.compiler.release>
        <minimalJavaBuildVersion>17</minimalJavaBuildVersion>
```

File: datawave-micrometer/pom.xml [hunk 3]
```diff
@@ -12,7 +12,7 @@
     <artifactId>datawave-micrometer</artifactId>
 
     <properties>
-        <maven.compiler.source>17</maven.compiler.source>
+        <maven.compiler.source>11</maven.compiler.source>
         <maven.compiler.target>17</maven.compiler.target>
```
Comment (ctubbsii) [inline datawave-micrometer/pom.xml]: You should probably do:

```suggestion
        <maven.compiler.release>11</maven.compiler.release>
        <maven.compiler.source>${maven.compiler.release}</maven.compiler.source>
        <maven.compiler.target>${maven.compiler.release}</maven.compiler.target>
```

File: datawave-micrometer/src/main/java/datawave/prometheus/DatawavePrometheusMeterRegistry.java [hunk 4]
```diff
@@ -62,7 +67,7 @@ public MeterRegistry create(MeterRegistryFactory.InitParameters params) {
             });
 
             new Thread(server::start).start();
-        } catch (IOException e) {
+        } catch (Throwable e) {
```
Comment (ctubbsii) [inline datawave-micrometer/src/main/java/datawave/prometheus/DatawavePrometheusMeterRegistry.java:67]: Catching Throwable is very bad practice. It catches Error types as well, which by definition are `serious problems that a reasonable application should not try to catch.`

If you want to include RTEs along with the checked exception, it'd be better to do:

```java
        } catch (IOException | RuntimeException e) {
```

But in this case, you're just rewrapping and throwing the RTE, so it doesn't make sense to catch the RTE here.

It also doesn't make sense to downgrade an Error to a RTE.

If there are additional checked exceptions, though, you could do this multi-catch solution, though.

File: datawave-micrometer/src/main/java/datawave/prometheus/DatawavePrometheusMeterRegistry.java [hunk 5]
```diff
@@ -62,7 +67,7 @@ public MeterRegistry create(MeterRegistryFactory.InitParameters params) {
...
             throw new RuntimeException(e);
```
Comment (ctubbsii) [inline datawave-micrometer/src/main/java/datawave/prometheus/DatawavePrometheusMeterRegistry.java]: It's better to throw a more specific RTE whenever possible. In this case, it's an IOException, so using UncheckedIOException makes sense:

```suggestion
            throw new UncheckedIOException(e);
```

File: datawave-micrometer/src/main/java/datawave/prometheus/DatawavePrometheusMeterRegistry.java (hunk 4 above)
Comment (ddanielr) [reply datawave-micrometer/src/main/java/datawave/prometheus/DatawavePrometheusMeterRegistry.java:67]: Just adding context.
The original reason for the `Throwable` catch statement was because the underlying code was throwing a "ClassNotFound" Exception but not putting that in the logs or killing the process. 
Instead, the code would still host the http endpoints, requests would hit the endpoint but return no body content.

Comment (ctubbsii) [reply datawave-micrometer/src/main/java/datawave/prometheus/DatawavePrometheusMeterRegistry.java:67]: If it's `ClassNotFoundException`, that's a checked exception. Usually those can be handled with a catch of the parent class, `ReflectiveOperationException`. If it's `NoClassDefFoundError`, that's not generally safe to recover from, and should not be handled (except as part of an effort to kill the process). That can be caused by a variety of things that can leave the JVM in an indeterministic and unpredictable state. For example, it can happen due to an exception in a static initializer that leaves the JVM in an unpredictable state, having partially initialized some static stuff that sticks around in the JVM and corrupts other threads.

So, I'd still avoid catching Throwable. It's pretty bad practice, and can lead to suppressing more severe errors like data corruption down the line. It's better to catch the checked and runtime exceptions only.
